pipeline {
    agent { label 'AGENT-1' }
    options{
        ansiColor('xterm')
    }
    stages {
        stage('Init') {
            steps {
                sh '''
                cd roboshop-infra-standard/01-vpc
                ls -ltr
                pwd
                terraform init
                '''
            }
        }
        stage('Plan') {
            steps {
                sh '''
                cd roboshop-infra-standard/01-vpc
                ls -ltr
                pwd
                terraform plan
                '''
            }
        }
        stage('approve'){
            steps{
                input "shall I apply?"
            }
        }
        stage('apply'){
        steps{
            sh '''
            echo 'applied'
            '''
        }
        }
    }
     post { 
        always { 
            echo 'I will always run whether the job fails or success'
        }
        success { 
            echo 'I will run only when the job is succeded'
        }
        failure { 
            echo 'I will run only when the job fails'
        }
    }
}