pipeline {
    agent { label 'AGENT-1' }

    stages {
        stage('Init') {
            steps {
                sh '''
                cd 01-vpc
                ls -ltr
                pwd
                terraform init
                '''
            }
        }
        stage('Plan') {
            steps {
                sh '''
                cd 01-vpc
                ls -ltr
                pwd
                terraform plan
                '''
            }
        }
    }
     post { 
        always { 
            echo 'I will always run whether the job fails or success'
        }
        success { 
            echo 'I will run only when the job is succeded'
        }
        failure { 
            echo 'I will run only when the job fails'
        }
    }
}